# ===============================================
# =         MASTER CONFIGURATION (TEMPLATE)
# = 모든 환경의 기반이 되는 기본 설정입니다.
# ===============================================

server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            scope:
              - email
              - profile
          meta:
            client-id: ${META_APP_ID}
            client-secret: ${META_APP_SECRET}
            scope:
              - user_profile
        provider:
          meta:
            user-info-uri: ${META_GRAPH_API_URL}/me

ai:
  server:
    url: ${AI_SERVER_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 30m
  refresh-token-validity: 7d

app:
  qr:
    local-path: "src/main/static-files/qr-images"
    web-path: "/qr-images/"
    size: 300
    format: "PNG"
  web-ar:
    base-url: "https://livingbrush.shop/ar/view"