# ===============================================
# =         PRODUCTION ENVIRONMENT CONFIGURATION
# = AWS EC2 + RDS 운영 환경을 위한 설정
# ===============================================

server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:5432}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    oauth2:
      client:
        provider:
          meta:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    profile-path: profile
  cloudfront:
    domain: ${CLOUDFRONT_DOMAIN}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://livingbrush.shop,https://www.livingbrush.shop}

app:
  qr:
    local-path: /app/static-files/qr-images
    web-path: /static-files/qr-images/
    size: 300
    format: PNG

  web-ar:
    base-url: ${WEB_AR_BASE_URL:https://livingbrush.shop}

  profile:
    default-image-url: ${DEFAULT_PROFILE_IMAGE_URL}

ai:
  server:
    url: ${AI_SERVER_URL}

logging:
  level:
    root: INFO
    com.bauhaus.livingbrushbackendapi: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
