# ===============================================
# = COMMON CONFIGURATION (BASECAMP)
# = Default settings for all environments
# ===============================================

server:
  port: 8888 # Default server port

spring:
  jpa:
    open-in-view: false # Recommended for performance
    hibernate:
      # Flyway가 스키마를 관리하므로, JPA는 코드와 DB가 일치하는지 '검증'만 하도록 설정합니다.
      # 이것이 가장 안전한 운영 표준입니다.
      ddl-auto: validate
    properties:
      hibernate:
        # N+1 문제 완화를 위한 기본 배치 사이즈 설정
        default_batch_fetch_size: 100
  flyway:
    # Flyway를 활성화하여 데이터베이스 스키마 변경을 관리합니다.
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Initial schema setup"

# Default AI server URL (can be overridden by profiles or environment variables)
ai:
  server:
    url: ${AI_SERVER_URL:http://127.0.0.1:58021}

# ===============================================
# = CORS Configuration
# ===============================================
cors:
  # Comma-separated list of allowed frontend origins.
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000