# ===============================================
# =         DOCKER CONTAINER ENVIRONMENT
# = Docker Compose로 실행할 때 사용합니다.
# ===============================================

spring:
  datasource:
    # Docker Compose 네트워크에서는 서비스 이름('postgres')으로 DB 컨테이너에 접근합니다.
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}

# 도커 환경에서도 SQL 로그는 보통 비활성화합니다.
# jpa.show-sql: false