# src/main/resources/application-local.yml

# Override the default port for the local environment
server:
  port: 8889 # Using a different port to avoid collision

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bauhaus_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # ... rest of your local configuration