# ===============================================
# =         PRODUCTION ENVIRONMENT CONFIGURATION
# = AWS EC2 + RDS 운영 환경을 위한 설정
# ===============================================

server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:5432}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  servlet:
    multipart:
      max-file-size: 50MB      # GLB 파일은 보통 5-20MB
      max-request-size: 50MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  # Redis Configuration (VR 로그인 토큰 관리)
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms # timeout도 같은 레벨로 맞춥니다.
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/{registrationId}"
        provider:
          meta:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    profile-path: profile
  cloudfront:
    domain: ${CLOUDFRONT_DOMAIN}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://livingbrush.shop,https://www.livingbrush.shop}

app:
  qr:
    local-path: /app/static-files/qr-images
    web-path: /static-files/qr-images/
    size: 300
    format: PNG

  web-ar:
    base-url: ${WEB_AR_BASE_URL:https://livingbrush.shop}

  profile:
    default-image-url: ${DEFAULT_PROFILE_IMAGE_URL}

ai:
  server:
    url: ${AI_SERVER_URL}

# ===================================================================
# Swagger/OpenAPI 3 Configuration for Production
# ===================================================================
springdoc:
  swagger-ui:
    # HTTPS 서버 URL 명시적 설정
    servers:
      - url: https://api.livingbrush.shop
        description: Production Server (HTTPS)
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.bauhaus.livingbrushbackendapi: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
